version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:10050
    volumes:
      - ./app:/app
    ports:
      - '10050:10050'
    env_file:
      - ./.env
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres-data:
    driver: local
